# Generated by Django 3.2.4 on 2021-06-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguareteAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(null=True),
        ),
    ]
